import { execSync } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";

interface EndpointHealth {
  name: string;
  file: string;
  url: string;
  status: number | string;
  ok: boolean;
  latencyMs?: number;
  uptimePercent?: number;
  history?: number[];
  consecutiveFailures?: number;
  firstFailedAt?: string;
  rotType?: string;
  eligibleForSunset?: boolean;
}

interface UptimeReport {
  lastChecked: string;
  totalChecked: number;
  activeReachable: number;
  deadUnreachable: number;
  healthPercent: number;
  status: string;
  endpoints: EndpointHealth[];
}

interface ResourceItem {
  name: string;
  [key: string]: unknown;
}

async function runSunset() {
  const isDryRun = process.argv.includes("--dry-run");
  const root = process.cwd();
  const uptimePath = path.join(root, "site", "uptime.json");

  console.log("🧹 [DevShelf Sunset Auditor] Checking for chronic link rot...\n");

  let uptimeReport: UptimeReport;
  try {
    const raw = await fs.readFile(uptimePath, "utf8");
    uptimeReport = JSON.parse(raw);
  } catch (err) {
    console.error("Could not load site/uptime.json. Run 'pnpm run check:links' first.", err);
    process.exit(0);
  }

  const eligible = (uptimeReport.endpoints || []).filter((ep) => ep.eligibleForSunset);

  if (eligible.length === 0) {
    console.log("✅ Zero dead resources qualify for automated sunset. Registry is healthy!");
    process.exit(0);
  }

  console.log(`⚠️ Found ${eligible.length} resource(s) eligible for automated sunsetting:\n`);

  // Target the first chronically dead resource for a dedicated, atomic Pull Request
  const target = eligible[0];
  console.log(`🎯 Sunsetting target: ${target.name} (${target.url})`);
  console.log(`   Shelf file:           ${target.file}`);
  console.log(`   Rot type:             ${target.rotType || "unreachable"}`);
  console.log(`   Consecutive failures: ${target.consecutiveFailures || "N/A"}`);
  console.log(`   First failed at:      ${target.firstFailedAt || "N/A"}\n`);

  const shelfFilePath = path.join(root, "shelf", target.file);
  const shelfContent = await fs.readFile(shelfFilePath, "utf8");
  const shelfItems: ResourceItem[] = JSON.parse(shelfContent.replace(/^\uFEFF/, ""));

  const initialCount = shelfItems.length;
  const filteredItems = shelfItems.filter(
    (item) => item.name.toLowerCase() !== target.name.toLowerCase(),
  );

  if (filteredItems.length === initialCount) {
    console.warn(`Could not find resource named '${target.name}' inside ${target.file}.`);
    process.exit(0);
  }

  if (isDryRun) {
    console.log(
      `[Dry Run] Would have removed '${target.name}' from ${target.file}. No changes made.`,
    );
    process.exit(0);
  }

  // Remove the dead resource from shelf file
  await fs.writeFile(shelfFilePath, `${JSON.stringify(filteredItems, null, 2)}\n`, "utf8");
  console.log(`✓ Removed '${target.name}' from shelf/${target.file}`);

  // Rebuild README and web app data
  console.log("🔨 Rebuilding README and web directory...");
  execSync("pnpm run build", { stdio: "inherit" });
  execSync("pnpm run format", { stdio: "inherit" });

  const slug = target.name.toLowerCase().replace(/[^a-z0-9]/g, "-");
  const branchName = `sunset/${slug}`;
  const prTitle = `[Cleanup] Sunset Dead Resource: ${target.name}`;

  const prBody = [
    `### 🧹 Automated Sunset of Dead Resource: ${target.name}`,
    "",
    "This automated Pull Request was generated by DevShelf's **Intelligent Link Rottenness & Healthcheck Auditor** because this resource has consistently failed availability audits.",
    "",
    "#### 📋 Audit Record",
    `- **Resource**: ${target.name}`,
    `- **Shelf File**: \`shelf/${target.file}\``,
    `- **Target URL**: ${target.url}`,
    `- **Rot Classification**: \`${target.rotType || "unreachable"}\``,
    `- **Consecutive Audit Failures**: ${target.consecutiveFailures || 3}`,
    `- **First Failure Detected**: ${target.firstFailedAt || "14+ days ago"}`,
    "",
    "#### 🔍 Why this action was taken",
    "DevShelf maintains strict quality curation for developers. Resources that display soft-404 errors, parked domain ads, expired SSL certificates, or persistent timeouts degrade community trust.",
    "",
    "#### 💡 Can this resource be restored?",
    "Yes! If the service comes back online or has moved to a new domain, maintainers or contributors can re-submit it via the [DevShelf Contribution Wizard](https://devshelf.ritualdev.in).",
    "",
    "---",
    "*Automated by DevShelf Sunset Workflow*",
  ].join("\n");

  const metadataPath = path.join(root, ".sunset-pr-metadata.json");
  await fs.writeFile(
    metadataPath,
    JSON.stringify({ branchName, prTitle, prBody, resourceName: target.name }, null, 2),
    "utf8",
  );

  console.log("\n🎉 Sunset PR metadata generated at .sunset-pr-metadata.json");
}

runSunset().catch((err) => {
  console.error("Sunset runner failed:", err);
  process.exit(1);
});
